import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import GlossaryPage from '../pages/GlossaryPage';

describe('GlossaryPage', () => {
  it('renders the glossary page with title', () => {
    render(<GlossaryPage />);
    expect(screen.getByText(/Climate Glossary/i)).toBeInTheDocument();
    expect(screen.getByText(/Explore key climate and sustainability terms/i)).toBeInTheDocument();
  });

  it('displays all glossary terms on initial load', () => {
    render(<GlossaryPage />);
    expect(screen.getByText('Carbon Footprint')).toBeInTheDocument();
    expect(screen.getByText('Greenhouse Effect')).toBeInTheDocument();
    expect(screen.getByText('Circular Economy')).toBeInTheDocument();
    expect(screen.getByText('Paris Agreement')).toBeInTheDocument();
    expect(screen.getByText('Net Zero')).toBeInTheDocument();
    expect(screen.getByText('Carbon Offset')).toBeInTheDocument();
    expect(screen.getByText('Biodiversity')).toBeInTheDocument();
  });

  it('displays all definitions on initial load', () => {
    render(<GlossaryPage />);
    expect(screen.getByText(/greenhouse gases.*generated by our actions/)).toBeInTheDocument();
    expect(screen.getByText(/economic system aimed at eliminating waste/)).toBeInTheDocument();
    expect(screen.getByText(/international treaty on climate change/)).toBeInTheDocument();
  });

  it('filters glossary by term name', async () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    
    fireEvent.change(searchInput, { target: { value: 'carbon' } });
    
    await waitFor(() => {
      // Should find 2 terms with "carbon" (Carbon Footprint and Carbon Offset)
      expect(screen.getByText(/2 of 7 terms/)).toBeInTheDocument();
      // Verify Greenhouse Effect is not shown (it doesn't contain "carbon")
      const allText = screen.getByText(/2 of 7 terms/).closest('div').textContent;
      expect(allText).not.toContain('Greenhouse Effect');
    });
  });

  it('filters glossary by definition content', async () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    
    fireEvent.change(searchInput, { target: { value: 'waste' } });
    
    await waitFor(() => {
      expect(screen.getByText('Circular Economy')).toBeInTheDocument();
      expect(screen.queryByText('Carbon Footprint')).not.toBeInTheDocument();
    });
  });

  it('performs case-insensitive search', async () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    
    fireEvent.change(searchInput, { target: { value: 'PARIS' } });
    
    await waitFor(() => {
      // Should find 1 term with "paris" (case-insensitive)
      expect(screen.getByText(/1 of 7 terms/)).toBeInTheDocument();
    });
  });

  it('shows no results message when search has no matches', async () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    
    fireEvent.change(searchInput, { target: { value: 'nonexistentterm' } });
    
    await waitFor(() => {
      expect(screen.getByText(/No terms found matching/)).toBeInTheDocument();
    });
  });

  it('updates term count based on search results', async () => {
    render(<GlossaryPage />);
    
    // Initial count should be 7
    expect(screen.getByText(/7 of 7 terms/)).toBeInTheDocument();
    
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    fireEvent.change(searchInput, { target: { value: 'carbon' } });
    
    // After filtering for "carbon", should show 2 of 7
    await waitFor(() => {
      expect(screen.getByText(/2 of 7 terms/)).toBeInTheDocument();
    });
  });

  it('clears search and shows all terms again', async () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    
    // Initial state should show all 7 terms
    expect(screen.getByText(/7 of 7 terms/)).toBeInTheDocument();
    
    // Search for something
    fireEvent.change(searchInput, { target: { value: 'circular' } });
    
    // After search, should show fewer terms
    await waitFor(() => {
      const termCount = screen.getByText(/of 7 terms/).textContent;
      expect(termCount).toContain('1 of 7');
    });
    
    // Clear search
    fireEvent.change(searchInput, { target: { value: '' } });
    
    // All terms should be visible again
    await waitFor(() => {
      expect(screen.getByText(/7 of 7 terms/)).toBeInTheDocument();
    });
  });

  it('highlights search query in results', async () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    
    fireEvent.change(searchInput, { target: { value: 'paris' } });
    
    await waitFor(() => {
      const termElement = screen.getByText(/paris/i);
      expect(termElement).toHaveClass('bg-yellow-200', 'dark:bg-yellow-800');
    });
  });

  it('searches partial text matches', async () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    
    fireEvent.change(searchInput, { target: { value: 'offset' } });
    
    await waitFor(() => {
      // "offset" should match "Carbon Offset" term - just check term count
      expect(screen.getByText(/1 of 7 terms/)).toBeInTheDocument();
    });
  });

  it('displays search tips section', () => {
    render(<GlossaryPage />);
    expect(screen.getByText(/Search Tips:/)).toBeInTheDocument();
    expect(screen.getByText(/Search by term name/)).toBeInTheDocument();
    expect(screen.getByText(/Search by definition content/)).toBeInTheDocument();
    expect(screen.getByText(/case-insensitive/)).toBeInTheDocument();
  });

  it('has accessible search input', () => {
    render(<GlossaryPage />);
    const searchInput = screen.getByPlaceholderText(/Search by term or definition/);
    expect(searchInput).toHaveAttribute('type', 'text');
    expect(searchInput).toHaveAttribute('aria-label', 'Search glossary');
  });
});
