import { useState, useMemo } from 'react';
import { Search, BookOpen } from 'lucide-react';

const GLOSSARY_TERMS = [
  {
    term: 'Carbon Footprint',
    definition: 'The total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.'
  },
  {
    term: 'Greenhouse Effect',
    definition: 'The trapping of the sun\'s warmth in a planet\'s lower atmosphere due to the greater transparency of the atmosphere to visible radiation than to infrared radiation.'
  },
  {
    term: 'Circular Economy',
    definition: 'An economic system aimed at eliminating waste and the continual use of resources by recycling and repairing.'
  },
  {
    term: 'Paris Agreement',
    definition: 'An international treaty on climate change adopted in 2015, targeting to limit global warming to well below 2°C, preferably to 1.5°C.'
  },
  {
    term: 'Net Zero',
    definition: 'Achieving a balance between the greenhouse gases put into the atmosphere and those taken out.'
  },
  {
    term: 'Carbon Offset',
    definition: 'A reduction in emissions of carbon dioxide or other greenhouse gases made in order to compensate for emissions made elsewhere.'
  },
  {
    term: 'Biodiversity',
    definition: 'The variety of life in the world or in a particular habitat or ecosystem.'
  }
];

export default function GlossaryPage() {
  const [searchQuery, setSearchQuery] = useState('');

  // Filter terms by search query (term or definition)
  const filteredTerms = useMemo(() => {
    if (!searchQuery.trim()) return GLOSSARY_TERMS;

    const lowerQuery = searchQuery.toLowerCase();
    return GLOSSARY_TERMS.filter(
      item =>
        item.term.toLowerCase().includes(lowerQuery) ||
        item.definition.toLowerCase().includes(lowerQuery)
    );
  }, [searchQuery]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800 p-4 md:p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-3">
            <BookOpen className="w-8 h-8 text-emerald-600 dark:text-emerald-400" />
            <h1 className="text-4xl font-bold text-slate-900 dark:text-white">
              Climate Glossary
            </h1>
          </div>
          <p className="text-slate-600 dark:text-slate-400 text-lg">
            Explore key climate and sustainability terms
          </p>
        </div>

        {/* Search Box */}
        <div className="mb-8">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-slate-400" />
            <input
              type="text"
              placeholder="Search by term or definition..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-12 pr-4 py-3 bg-white dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-lg text-slate-900 dark:text-white placeholder-slate-500 dark:placeholder-slate-400 focus:outline-none focus:border-emerald-500 dark:focus:border-emerald-400 transition-colors"
              aria-label="Search glossary"
            />
          </div>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-2">
            {filteredTerms.length} of {GLOSSARY_TERMS.length} terms
          </p>
        </div>

        {/* Glossary Terms */}
        {filteredTerms.length > 0 ? (
          <div className="space-y-4">
            {filteredTerms.map((item, index) => {
              // Highlight search query in term and definition
              const highlightText = (text, query) => {
                if (!query.trim()) return text;
                
                const parts = text.split(new RegExp(`(${query})`, 'gi'));
                return parts.map((part, i) =>
                  part.toLowerCase() === query.toLowerCase() ? (
                    <span key={i} className="bg-yellow-200 dark:bg-yellow-800 font-semibold">
                      {part}
                    </span>
                  ) : (
                    part
                  )
                );
              };

              return (
                <div
                  key={index}
                  className="bg-white dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700 p-6 hover:shadow-lg dark:hover:shadow-slate-900/50 transition-shadow"
                >
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                    {highlightText(item.term, searchQuery)}
                  </h3>
                  <p className="text-slate-700 dark:text-slate-300 leading-relaxed">
                    {highlightText(item.definition, searchQuery)}
                  </p>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="bg-white dark:bg-slate-800 rounded-lg border-2 border-dashed border-slate-300 dark:border-slate-600 p-12 text-center">
            <BookOpen className="w-12 h-12 text-slate-400 dark:text-slate-500 mx-auto mb-3" />
            <p className="text-slate-600 dark:text-slate-400 text-lg">
              No terms found matching "{searchQuery}"
            </p>
            <p className="text-slate-500 dark:text-slate-500 text-sm mt-2">
              Try searching for a different term or keyword
            </p>
          </div>
        )}

        {/* Quick Tips */}
        <div className="mt-12 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-6">
          <h4 className="font-bold text-blue-900 dark:text-blue-200 mb-3">💡 Search Tips:</h4>
          <ul className="space-y-2 text-blue-800 dark:text-blue-300 text-sm">
            <li>• Search by term name (e.g., "carbon footprint")</li>
            <li>• Search by definition content (e.g., "greenhouse gases")</li>
            <li>• Search is case-insensitive and matches partial text</li>
            <li>• Clear the search box to see all terms</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
