import { useState, useMemo } from 'react';
import { GraduationCap, Award, BookOpen, CheckCircle2, AlertCircle, X, Download } from 'lucide-react';
import Button from '../components/ui/Button';
import TextInput from '../components/ui/TextInput';
import WeatherAqi from '../components/WeatherAqi';

const COURSES = [
  {
    id: 'basics',
    title: 'Climate Change Basics',
    description: 'Learn about the greenhouse effect, global emissions, and climate targets.',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    content: 'Greenhouse gases like Carbon Dioxide (CO₂) and Methane (CH₄) trap solar heat in the Earth\'s atmosphere, warming the planet. Human activities—principally burning fossil fuels for energy, transportation, and industrial farming—have elevated carbon concentrations from 280 ppm in pre-industrial times to over 420 ppm today. The Paris Agreement seeks to limit warming to 1.5°C to avoid catastrophic feedback loops.',
    quiz: [
      {
        question: 'What is the primary greenhouse gas emitted by human fossil fuel combustion?',
        options: ['Carbon Dioxide (CO₂)', 'Oxygen', 'Helium', 'Nitrogen'],
        answer: 0
      },
      {
        question: 'What is the warming threshold target set by the Paris Agreement?',
        options: ['3.0°C', '2.0°C', '1.5°C', '0.5°C'],
        answer: 2
      }
    ]
  },
  {
    id: 'renewable',
    title: 'Renewable Energy Systems',
    description: 'Understand solar, wind, and geothermal grids replacing fossil fuels.',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4',
    content: 'Renewable energy systems harness infinite natural flows (sunlight, wind, heat, water) to generate electricity. Solar photovoltaic (PV) panels absorb photons to release electrons, producing DC current. Wind turbines convert kinetic energy of airflow into mechanical energy and then electric power. Transitioning national grids to renewable power is the highest impact carbon reduction strategy globally.',
    quiz: [
      {
        question: 'Which device absorbs photons from sunlight to generate electricity?',
        options: ['Steam Turbine', 'Solar Photovoltaic Panel', 'Inverter', 'Geothermal Pump'],
        answer: 1
      },
      {
        question: 'What is the main environmental benefit of renewable grids?',
        options: ['No space requirements', 'Infinite transmission speed', 'Zero carbon emissions during operation', 'Easier maintenance'],
        answer: 2
      }
    ]
  },
  {
    id: 'lifestyle',
    title: 'Sustainable Living & Action',
    description: 'Master waste reduction, composting, and circular economy concepts.',
    content: 'A sustainable lifestyle minimizes resource consumption and environmental impact. The circular economy shifts society from a linear "take-make-waste" model to a loop where items are designed to be repaired, reused, and recycled. Composting organic waste diverts methane-producing waste from landfills, locking nutrients back into soils. Small habits—like carrying reusable water bottles—compound into substantial carbon offsets.',
    quiz: [
      {
        question: 'What is the primary goal of a "circular economy"?',
        options: ['To print more paper money', 'To eliminate waste by design and reuse materials', 'To build circular houses', 'To increase consumer spending'],
        answer: 1
      },
      {
        question: 'Diverting organic waste to composting prevents the release of which potent landfill gas?',
        options: ['Oxygen', 'Methane', 'Argon', 'Hydrogen'],
        answer: 1
      }
    ]
  }
];

const GLOSSARY = [
  { term: 'Carbon Footprint', definition: 'The total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.' },
  { term: 'Greenhouse Effect', definition: 'The trapping of the sun\'s warmth in a planet\'s lower atmosphere due to the greater transparency of the atmosphere to visible radiation than to infrared radiation.' },
  { term: 'Circular Economy', definition: 'An economic system aimed at eliminating waste and the continual use of resources by recycling and repairing.' },
  { term: 'Paris Agreement', definition: 'An international treaty on climate change adopted in 2015, targeting to limit global warming to well below 2°C, preferably to 1.5°C.' },
  { term: 'Net Zero', definition: 'Achieving a balance between the greenhouse gases put into the atmosphere and those taken out.' },
  { term: 'Carbon Offset', definition: 'A reduction in emissions of carbon dioxide or other greenhouse gases made in order to compensate for emissions made elsewhere.' },
  { term: 'Biodiversity', definition: 'The variety of life in the world or in a particular habitat or ecosystem.' }
];

export default function LearnPage({ addXp, user, gamification }) {
  const [activeCourse, setActiveCourse] = useState(null);
  const [quizAnswers, setQuizAnswers] = useState({});
  const [quizSubmitted, setQuizSubmitted] = useState(false);
  const [quizErrors, setQuizErrors] = useState(null);
  const [viewingCert, setViewingCert] = useState(null);
  const [glossarySearch, setGlossarySearch] = useState('');

  // Track completed courses locally/persisted
  const [completedCourses, setCompletedCourses] = useState(() => {
    try {
      const stored = localStorage.getItem('carbon_completed_courses');
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });

  const handleStartCourse = (course) => {
    setActiveCourse(course);
    setQuizAnswers({});
    setQuizSubmitted(false);
    setQuizErrors(null);
  };

  const handleSelectOption = (questionIdx, optionIdx) => {
    setQuizAnswers(prev => ({
      ...prev,
      [questionIdx]: optionIdx
    }));
  };

  const handleSubmitQuiz = () => {
    if (!activeCourse) return;
    
    // Validate that all questions are answered
    const unanswered = activeCourse.quiz.some((_, idx) => quizAnswers[idx] === undefined);
    if (unanswered) {
      setQuizErrors('Please answer all questions before submitting.');
      return;
    }

    // Check answers
    const allCorrect = activeCourse.quiz.every((q, idx) => quizAnswers[idx] === q.answer);
    
    if (allCorrect) {
      setQuizSubmitted(true);
      setQuizErrors(null);
      
      if (!completedCourses.includes(activeCourse.id)) {
        const nextCompleted = [...completedCourses, activeCourse.id];
        setCompletedCourses(nextCompleted);
        try {
          localStorage.setItem('carbon_completed_courses', JSON.stringify(nextCompleted));
        } catch {
          // Ignore localStorage write failures in restricted environments
        }
        addXp(150); // XP reward for passing quiz
      }
    } else {
      setQuizErrors('Some answers were incorrect. Please review the course materials and try again.');
    }
  };

  const filteredGlossary = useMemo(() => {
    return GLOSSARY.filter(item => 
      item.term.toLowerCase().includes(glossarySearch.toLowerCase()) ||
      item.definition.toLowerCase().includes(glossarySearch.toLowerCase())
    );
  }, [glossarySearch]);

  return (
    <div className="space-y-8 animate-fade-in text-left font-jakarta">
      
      {/* Top Banner */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-805 p-6 rounded-3xl shadow-sm glass-card flex items-center gap-4">
        <div className="p-3 bg-emerald-500/10 text-emerald-500 rounded-2xl">
          <GraduationCap size={28} />
        </div>
        <div>
          <h2 className="text-3xl font-extrabold font-outfit text-slate-800 dark:text-slate-100">Climate Academy</h2>
          <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">Study environmental concepts, complete quizzes, and unlock certified badges.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Side: Courses List */}
        <div className="lg:col-span-2 space-y-5">
          <div className="bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-850 p-6 rounded-3xl shadow-sm glass-card">
            <h3 className="text-xl font-bold font-outfit text-slate-850 dark:text-slate-100 mb-4">Core Mini Courses</h3>
            
            <div className="space-y-4">
              {COURSES.map(course => {
                const isDone = completedCourses.includes(course.id);
                return (
                  <div 
                    key={course.id} 
                    className="p-5 bg-slate-50 dark:bg-slate-800/20 border border-slate-100 dark:border-slate-850 rounded-2xl flex flex-col md:flex-row justify-between items-start md:items-center gap-4 hover:shadow-sm transition"
                  >
                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className="text-base font-bold font-outfit text-slate-800 dark:text-slate-200">{course.title}</h4>
                        {isDone && <span className="text-xs bg-emerald-500/10 text-emerald-500 font-bold px-2 py-0.5 rounded-full">Completed</span>}
                      </div>
                      <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">{course.description}</p>
                    </div>
                    <div className="flex gap-2 w-full md:w-auto">
                      <Button
                        type="button"
                        onClick={() => handleStartCourse(course)}
                        className="flex-1 md:flex-initial"
                      >
                        Start Learning
                      </Button>
                      {isDone && (
                        <Button
                          type="button"
                          onClick={() => setViewingCert(course)}
                          variant="secondary"
                          className="px-3 py-2"
                          title="View Certificate"
                        >
                          <Award size={15} />
                        </Button>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right Side: Glossary */}
        <div className="space-y-5">
          <div className="bg-white dark:bg-slate-900 border border-slate-200/60 dark:border-slate-850 p-6 rounded-3xl shadow-sm glass-card max-h-[420px] flex flex-col">
            <h3 className="text-lg font-bold font-outfit text-slate-850 dark:text-slate-100 mb-3 flex items-center gap-1.5">
              <BookOpen size={18} />
              Eco Glossary
            </h3>
            
            {/* Search */}
            <div className="relative mb-4 flex-shrink-0">
              <TextInput
                id="glossary-search"
                label="Search glossary terms"
                description="Search by term or definition."
                value={glossarySearch}
                onChange={(e) => setGlossarySearch(e.target.value)}
                className="mb-0"
                placeholder="Search terms..."
              />
            </div>

            {/* Terms list */}
            <div className="flex-1 overflow-y-auto space-y-3 pr-1">
              {filteredGlossary.map((item, idx) => (
                <div key={idx} className="p-3 bg-slate-50 dark:bg-slate-800/20 border border-slate-100 dark:border-slate-850 rounded-xl">
                  <h4 className="text-xs font-bold text-slate-800 dark:text-slate-200">{item.term}</h4>
                  <p className="text-[10px] text-slate-500 dark:text-slate-400 mt-1 leading-normal">{item.definition}</p>
                </div>
              ))}
              {filteredGlossary.length === 0 && (
                <div className="text-center py-6 text-xs text-slate-400">No glossary terms matched.</div>
              )}
            </div>
          </div>
          {/* Live Weather/AQI */}
          <div className="mt-4">
            <WeatherAqi />
          </div>
        </div>
      </div>

      {/* Active Course Modal / Reader */}
      {activeCourse && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm">
          <div className="w-full max-w-2xl bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 p-6 md:p-8 shadow-2xl relative max-h-[90vh] overflow-y-auto">
            <button
              onClick={() => setActiveCourse(null)}
              className="absolute top-4 right-4 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 p-1 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"
            >
              <X size={20} />
            </button>

            <h3 className="text-2xl font-bold font-outfit text-slate-850 dark:text-slate-100 mb-4">{activeCourse.title}</h3>
            
            {/* Course Material Content */}
            {/* Optional Video */}
            {activeCourse.videoUrl && (
              <div className="mb-4 rounded-2xl overflow-hidden border border-slate-100 dark:border-slate-850">
                <video controls className="w-full h-auto bg-black">
                  <source src={activeCourse.videoUrl} />
                  Your browser does not support the video tag.
                </video>
              </div>
            )}

            <div className="p-5 bg-slate-50 dark:bg-slate-800/30 border border-slate-100 dark:border-slate-850 rounded-2xl leading-relaxed text-sm text-slate-700 dark:text-slate-300">
              {activeCourse.content}
            </div>

            {/* Quiz Section */}
            <div className="mt-8 pt-6 border-t border-slate-100 dark:border-slate-850 space-y-6">
              <h4 className="text-lg font-bold font-outfit text-slate-800 dark:text-slate-200 flex items-center gap-1.5">
                <CheckCircle2 className="text-emerald-500" size={18} />
                Course Checkpoint Quiz
              </h4>

              {quizErrors && (
                <div className="p-3.5 bg-red-500/10 text-red-600 dark:text-red-400 rounded-xl text-xs flex items-center gap-2 border border-red-500/10">
                  <AlertCircle size={15} />
                  {quizErrors}
                </div>
              )}

              {quizSubmitted ? (
                <div className="p-5 bg-emerald-500/5 border border-emerald-300 dark:border-emerald-800/30 rounded-2xl flex flex-col items-center justify-center text-center space-y-3">
                  <span className="text-4xl animate-bounce">🎓</span>
                  <h5 className="font-bold text-slate-850 dark:text-slate-100">Congratulations, you passed!</h5>
                  <p className="text-xs text-slate-500 dark:text-slate-450 max-w-xs leading-normal">
                    You earned <strong className="text-emerald-500">+150 XP</strong> and unlocked the course certificate!
                  </p>
                  <Button
                    type="button"
                    onClick={() => {
                      setViewingCert(activeCourse);
                      setActiveCourse(null);
                    }}
                    className="px-4 py-2 flex items-center gap-1.5"
                  >
                    <Award size={14} />
                    View Certificate
                  </Button>
                </div>
              ) : (
                <div className="space-y-5">
                  {activeCourse.quiz.map((q, qIdx) => (
                    <div key={qIdx} className="space-y-2.5">
                      <div className="text-xs font-bold text-slate-400 uppercase tracking-wider">Question {qIdx + 1}</div>
                      <p className="text-sm font-semibold text-slate-700 dark:text-slate-200 leading-normal">{q.question}</p>
                      
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        {q.options.map((opt, oIdx) => {
                          const isSelected = quizAnswers[qIdx] === oIdx;
                          return (
                            <button
                              key={oIdx}
                              onClick={() => handleSelectOption(qIdx, oIdx)}
                              className={`p-3 text-left text-xs font-semibold rounded-xl border transition-all ${
                                isSelected
                                  ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/20 text-emerald-600 dark:text-emerald-400 scale-[1.01]'
                                  : 'border-slate-100 dark:border-slate-850 hover:bg-slate-50 dark:hover:bg-slate-800/20 text-slate-600 dark:text-slate-350'
                              }`}
                            >
                              {opt}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  ))}

                  <Button
                    type="button"
                    onClick={handleSubmitQuiz}
                    className="w-full"
                  >
                    Submit Quiz Answers
                  </Button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Certificate Display Overlay */}
      {viewingCert && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
          <div className="w-full max-w-2xl bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 p-6 md:p-8 shadow-2xl relative flex flex-col items-center">
            <button
              onClick={() => setViewingCert(null)}
              className="absolute top-4 right-4 text-slate-400 hover:text-slate-650 p-1 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800"
              aria-label="Close certificate viewer"
            >
              <X size={20} />
            </button>

            {/* Certificate Template */}
            <div className="border-[8px] border-emerald-500/20 p-6 w-full rounded-2xl relative bg-emerald-50/10 dark:bg-slate-950/40 text-center font-outfit shadow-inner">
              <span className="text-xs font-bold text-emerald-500 tracking-widest block mb-4 uppercase">Certificate of Completion</span>
              
              <h4 className="text-3xl font-extrabold text-slate-800 dark:text-slate-100">CLIMATORA ACADEMY</h4>
              <p className="text-xs text-slate-400 mt-2">This certifies that</p>
              
              <div className="my-6 border-b border-dashed border-emerald-500/30 max-w-xs mx-auto pb-2">
                <span className="text-xl font-bold text-slate-700 dark:text-slate-200">{user?.name || 'Sunrise Steward'}</span>
              </div>
              
              <p className="text-xs text-slate-500 dark:text-slate-400 max-w-sm mx-auto leading-normal">
                has successfully completed all lectures, reading modules, and checkpoint examinations for the curriculum:
              </p>
              <h5 className="text-base font-extrabold text-emerald-600 dark:text-emerald-400 mt-3">{viewingCert.title}</h5>

              <div className="flex justify-between items-end mt-10 px-6">
                <div className="text-left text-[10px] text-slate-400">
                  <span>Authorized Signature</span>
                  <div className="border-t border-slate-200 dark:border-slate-800 pt-1 mt-6 font-semibold">Climatora AI Board</div>
                </div>
                {/* Stamp */}
                <div className="w-16 h-16 rounded-full border-4 border-dashed border-emerald-500 flex items-center justify-center text-emerald-500 transform rotate-12 font-bold text-xs select-none">
                  APPROVED
                </div>
                <div className="text-right text-[10px] text-slate-400">
                  <span>Certification ID</span>
                  <div className="border-t border-slate-200 dark:border-slate-800 pt-1 mt-6 font-semibold">CC-{viewingCert.id.toUpperCase()}-{gamification.xp}</div>
                </div>
              </div>
            </div>

            <Button
              type="button"
              onClick={() => window.print()}
              className="mt-6 px-6 py-3 flex items-center gap-1.5"
            >
              <Download size={15} />
              Print Certificate
            </Button>
          </div>
        </div>
      )}

    </div>
  );
}
